### ISSUE TITLE
ESC & Function  key not working.

### ISSUE THREAD

**Issue by mortuzahossain** [VinylNerd/ThinkPad-T440P-OpenCore#3] opened 2021-06-09 19:56 UTC
I am using your v0.4-beta1 and after that, I am noticing that the ESC key of my keyboard is not detecting and function key also.
If I use an external keyboard then the ESC key is functional.
In many situations, I need the ESC key very badly and it is missing. Is there any fix?

Your help is highly needed.

Thank you.

**Comment by VinylNerd** [comment] 2021-06-09 21:38
yes

this is what you want

https://github.com/MSzturc/ThinkpadAssistant/releases/tag/v1.9.2.1

i will close the issue in 7 days if no reply

**Comment by mortuzahossain** [comment] 2021-06-10 04:10
Function keys are working but what about the ESC key. It is not working.

**Comment by VinylNerd** [comment] 2021-06-10 08:25
as far as i know the ESC key works for me, please provide an example where it does not work for you and i will try to recreate to understand if this issue is unique to your device or my EFI

**Comment by mortuzahossain** [comment] 2021-06-10 08:35
![Screenshot 2021-06-10 at 2 33 07 PM](https://user-images.githubusercontent.com/14279461/121492672-e0788800-c9f8-11eb-93be-8be729d18aaf.png)
This is my keyboard configuration. But when I press the ESC key on my keyboard it is not detecting clicks in any places.

**Comment by VinylNerd** [comment] 2021-06-10 09:20
ESC key is 100% confirmed to be working fine for me in MacOS and windows, does the ESC key work for you in windows?

i use this https://en.key-test.ru/

**Comment by mortuzahossain** [comment] 2021-06-10 09:48
Using the website, I see that ESC not working in both windows or mac. Don't know if the key is broken or not? Need to install windows for testing which I really don't want. But if I use a USB keyboard it is taking input from that and working ESC fine from an external keyboard.

By the way, thank you so much for putting such kind and good effort into this repository. 
Thank you so much.

**Comment by VinylNerd** [comment] 2021-06-10 10:17
Yes it seems your keyboard may be broken but its hard to tell, there is a very small possibility that your thinkpad model has some difference causing this, but i have no idea what it would be, probably best to buy a new keyboard which has a 30 day return policy and install that and test.

Thank you for your feedback and kind words :)

**Closed as completed** 2021-06-18 09:30 UTC
