### ISSUE TITLE
Help! it randomly makes me quit all applications and doesn't let me open them. To fix I have to reboot.

### ISSUE THREAD

**Issue by Thevirtualmask** [VinylNerd/ThinkPad-T440P-OpenCore#6] opened 2021-07-02 17:13 UTC
hello, after some time, the computer gives this problem. It happens both when I use the browser or Visual Studio or any program like logic. To fix I have to reboot. The EFI is the same as the last release (obviously I entered my SMBIOS) and I have not changed any kext. 

https://user-images.githubusercontent.com/49619464/124308350-07b90580-db1e-11eb-82d5-c9fd0b43adc9.mp4

**Comment by VinylNerd** [comment] 2021-07-02 17:20
Hello, same thing has happened to me 2 or 3 times now, and not for a week, im not sure what triggered it but im trying to figure it out so it can be fixed, if you have any logs or info which points to whats creating the issue let me know, otherwise its totaly possible that its a bug with 11.4 i just havnt spent any time looking into it. i suggest posting this video in hackintosh reddit and if you get any response or info on a fix PLZ let me know, thanks i will leave this issue open.

**Comment by Thevirtualmask** [comment] 2021-07-06 13:24
hi, this problem figure when i open Logic, Visual studio or other heavy program. So idk

**Comment by VinylNerd** [comment] 2021-07-13 08:21
yeah hard to say, well i am now on opencore 0.7.1 and will upload this build by the end of the week and i havnt seen the issue in a while so lets hope its fixed :)

**Comment by VinylNerd** [comment] 2021-07-29 10:53
please let me know if you are still having this issue with the latest build and macOS 11.5.1

**Comment by SinaGamer55** [comment] 2021-07-30 00:38
> please let me know if you are still having this issue with the latest build and macOS 11.5.1

Hello, I’ve upgraded my laptop from Catalina to Big Sur about a month ago and the exact same issue happens for me after opening some apps which is very frustrating...
I’ve tried everything: reinstalling the os, tinkering with config.plist, changing smbios, disabling icloud, updating to 11.5.1 and....
By searching over and over I found this issue posted here. 
My laptop specs: Asus K56c, Ivy Bridge i5-3337u, 6GB ram, Intel hd 4000 gpu.
I checked thevirtualmask’s reddit post and he says it was fixed by checking his config.plist.
Also I compared the efi folder you just uploaded with mine, but there wasn’t so much difference. Did you do something specific to fix it or it got fixed by itself?
Thank you for uploading your files though, I appreciate your help

**Comment by VinylNerd** [comment] 2021-07-30 10:00
@Thevirtualmask what did you change in the config to fix the issue? could you share, i cant find said reddit post @SinaGamer55

**Comment by VinylNerd** [comment] 2021-07-30 10:03
in my next build i will be including CpuTscSync kext to try to help with this issue, so far it has not occured for me on 11.5.1 with this on the build however i did have a complete freeze last night, so i moved my macOS SSD from the Caddy into the original 2.5 sata slot

if i am unable to go extended time without issue i will report back on the weekend or monday

**Comment by SinaGamer55** [comment] 2021-07-30 10:46
> @Thevirtualmask what did you change in the config to fix the issue? could you share, i cant find said reddit post @SinaGamer55

Here’s the link:
https://www.reddit.com/r/hackintosh/comments/of4ndt/help_it_randomly_makes_me_quit_all_applications/

**Comment by VinylNerd** [comment] 2021-07-30 10:55
thanks, i have replied there, hope to find the fix

**Comment by SinaGamer55** [comment] 2021-07-30 11:01
> in my next build i will be including CpuTscSync kext to try to help with this issue, so far it has not occured for me on 11.5.1 with this on the build however i did have a complete freeze last night, so i moved my macOS SSD from the Caddy into the original 2.5 sata slot
> 
> if i am unable to go extended time without issue i will report back on the weekend or monday

I don’t think CpuTscSync will help, as recommended here:
 https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#macos-frozen-right-before-login

You made a good move with the ssd, because I’ve read in many places that the internal hdd should be replaced with the ssd, otherwise there’ll be issues...
I’ll upload the part of the system log that the crash happened for me.. It had some useful information... you can also check your log by opening Console, then opening system.log (you have to know when your problem happened...)

**Comment by SinaGamer55** [comment] 2021-07-30 11:14
[crashlog.pdf](https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/files/6907116/crashlog.pdf)

Here's the pdf. Sorry for the formatting... Why can't TextEdit save as .txt though?
There are mentions of the Graphics driver for me... maybe it's a graphics issue?
You can check your logs too, though it's usually not helpful...

**Comment by VinylNerd** [comment] 2021-08-01 09:00
i still havnt had a freeze up again since using the standard 2.5'' drive bay and CpuTscSync

**Comment by SinaGamer55** [comment] 2021-08-02 13:31
> i still havnt had a freeze up again since using the standard 2.5'' drive bay and CpuTscSync

Hello again. I don't have any crashes anymore and the reason was that I had disabled the quirk named AppleXcpmCfgLock.
As you may know, there's no Xcpm (power management) for Ivy Bridge natively and the quirk I mentioned only applies to Haswell (your laptop) and higher cpus.
I have an Ivy Bridge cpu and couldn't upgrade to Big Sur without changing my smbios to a Haswell one first. So after changing it, I forgot to enable that quirk, thus causing issues in macOS.
Although it was fine in Catalina (except for some kernel panics), Big Sur crashed the applications and got worse.
I enabled that quirk and seemingly it's ok now.
So the fix for this issue was enabling the AppleXcpmCfgLock for me.

Thanks a lot for posting your builds.
Now you can close this issue if you want to.

**Comment by VinylNerd** [comment] 2021-08-02 14:46
> > i still havnt had a freeze up again since using the standard 2.5'' drive bay and CpuTscSync
> 
> Hello again. I don't have any crashes anymore and the reason was that I had disabled the quirk named AppleXcpmCfgLock.
> As you may know, there's no Xcpm (power management) for Ivy Bridge natively and the quirk I mentioned only applies to Haswell (your laptop) and higher cpus.
> I have an Ivy Bridge cpu and couldn't upgrade to Big Sur without changing my smbios to a Haswell one first. So after changing it, I forgot to enable that quirk, thus causing issues in macOS.
> Although it was fine in Catalina (except for some kernel panics), Big Sur crashed the applications and got worse.
> I enabled that quirk and seemingly it's ok now.
> So the fix for this issue was enabling the AppleXcpmCfgLock for me.
> 
> Thanks a lot for posting your builds.
> Now you can close this issue if you want to.

i have this quirk enabled and i am still having the issue, even since making this post i still was required to reboot yesterday evening, i have not had any full system lockups since switching SSD bay and using CpuTscSync but i am looking for a fix to resolve this as it causes a reboot every 2-3 days

**Comment by SinaGamer55** [comment] 2021-08-02 23:43
> 
> i have this quirk enabled and i am still having the issue, even since making this post i still was required to reboot yesterday evening, i have not had any full system lockups since switching SSD bay and using CpuTscSync but i am looking for a fix to resolve this as it causes a reboot every 2-3 days

Oh, I thought you only had freezes and didn't have this issue anymore..
I've just looked at your config.plist (in your latest release) and you have AppleCpuPmCfgLock quirk disabled (though the other one is enabled).
you can test with this quirk enabled and see how it goes. Also don't forget to keep a backup usb efi drive in case it doesn't boot.

**Comment by VinylNerd** [comment] 2021-08-03 09:28
yes, i noticed that and enabled AppleCpuPmCfgLock aswell, this change will be included in the next build with OpenCore 0.7.2 which i will upload today

**Comment by EdsonLuiz** [comment] 2021-08-10 12:44
Sorry, but this looks like an internet issue. When the computer cannot communicate with apple services properly, to verify the authenticity of the applications, the applications do not open until the connection is reset or re-established. In the video it appears that your WIFI connection is down.

**Comment by VinylNerd** [comment] 2021-08-18 21:42
i have had the same issue and it definately wasnt internet related but i believe i have it fixed now, will be looking for people to confirm this after the next build goes up in early september

**Comment by karnadii** [comment] 2021-08-21 04:25
I encounter this issue too, hope it fixes in next release thanks

**Comment by VinylNerd** [comment] 2021-08-29 09:46
i have it fixed now, along with SD card support working, expect to see the next release in the next week after OpenCore 0.7.3 is released :) i will leave this open for some people to confirm the problem is solved in the next release.

**Comment by VinylNerd** [comment] 2021-09-07 10:25
for anyone with this issue please try the new build and report if you are still having issues

https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/releases

**Comment by karnadii** [comment] 2021-09-11 15:10
I still having the issue after upgrade

**Comment by VinylNerd** [comment] 2021-09-11 17:10
@karnadii which version of macOS are you using? 11.5.2? if not try to update

**Comment by karnadii** [comment] 2021-09-12 05:16
> @karnadii which version of macOS are you using? 11.5.2? if not try to update

Already updated to 11.5.2. but I don't use voltage shift. Should I enable voltage shift?

**Comment by logasans** [comment] 2021-10-10 02:22
hello, i am having the same problem as you all. same laptop, different efi. i tried your efi, then no luck. it turns out, it's a bus error. the temporary solution is to reinstall your os. trying to reset nvram did not work
[ReportCrash_2021-09-30-212720_MacBook-Pro.txt](https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/files/7316726/ReportCrash_2021-09-30-212720_MacBook-Pro.txt)
.

**Comment by VinylNerd** [comment] 2021-11-16 11:17
@logasans thanks, so resinstalling your OS fixed it for you? ive been hoping that an update to opencore or something would fix it but im not sure, overall the issue seems to happen to me about once a day now

**Comment by SinaGamer55** [comment] 2021-11-16 15:19
Hi everyone, I almost forgot about this issue being open here. I found a final solution yesterday (hopefully).
Unfortunately this issue didn't stop happening for me completely. Although apps stopped crashing on my laptop, but corebrightnessd (the daemon responsible for Night Shift) would crash almost everyday, and brightness slider, night shift and many other things wouldn't work without a full restart.
Anyways, yesterday I found this by searching the web:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/564
Apparently the kext FeatureUnlock is responsible for this (which is present in @VinylNerd 's builds). I disabled it and I don't have any issues anymore.
Some reported that it doesn't happen for them on Monterey. The kext developer has also released a new version in OCLP's kexts folder, but it didn't fix the issue for me (maybe it works for you?):
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Acidanthera/FeatureUnlock-v1.0.4-RELEASE.zip
So, I want you all to either **add `-caroff` to boot-args in your config file** or to **disable this kext** completely and report back here if the issue still happens for you or not.

**Comment by VinylNerd** [comment] 2021-11-16 16:09
thanks sooo much for this! im gonna try the 1.0.4 and if it doesnt work ill be disabling it and uploading my next build without FeatureUnlock once i find out what features will be lost because of it, cheers!

**Comment by VinylNerd** [comment] 2021-11-16 21:26
another thing to note is that this issue was first documented july 2 after the v0.4-beta1 release included sidecar fixup (the first version of feature unlock) so it makes sense that kext was what induced the problem. I'm currently running the 1.0.4 beta version of the feature unlock kext and have not had an issue yet, but i need more days to see.

**Comment by SinaGamer55** [comment] 2021-11-16 22:20
> thanks sooo much for this! 

You're welcome!
> once i find out what features will be lost because of it

It adds Sidecar, Nightshift and two other Monterey-exclusive features afaik.
I didn't know our SMBIOS (MBP Late 2013) natively supported nightshift, so for me its absence does nothing as Sidecar wasn't useful for me anyway (my ipad didn't support it)
So I think removing it wouldn't make things noticeably different...
> another thing to note is that this issue was first documented july 2 after the v0.4-beta1 release included sidecar fixup

Good point! We could identify the culprit just by looking at the difference between your builds... but anyway, just forget about it...

**Comment by VinylNerd** [comment] 2021-11-27 00:12
new version updated with the fix, ill leave this open for a bit longer incase it will help anyone with the same issue find the new build 

https://github.com/VinylNerd/ThinkPad-T440P-OpenCore/releases/tag/v0.5-beta2

cheers for the fix!

**Comment by VinylNerd** [comment] 2021-12-06 16:26
issue resolved as of v0.5-beta2

thanks to everyone who helped to solve this! especially @SinaGamer55

**Closed as completed by VinylNerd** 2021-12-06 16:26 UTC
